baseURL = "https://hugo-modus.yejun.dev/"
title = "hugo-modus"
copyright = "&copy; 2025"
defaultContentLanguage = "en"
enableRobotsTXT = false

[params]
description = "An opinionated Hugo theme using the [colour palette of the Modus themes](https://protesilaos.com/emacs/modus-themes-colors)."
toc = true

[taxonomies]
  series = "series"

[markup]
  [markup.highlight]
    noClasses = false

[menus]
  [[menus.main]]
    name = "Series"
    pageRef = "/series"
    weight = 10
  [[menus.main]]
    name = "GitHub"
    url = "https://github.com/goofansu/hugo-modus"
    weight = 20

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
  [languages.zh]
    languageName = "中文"
    weight = 20

[outputs]
  page = ["html", "markdown"]
