;;; generate-publish.el --- Publish Org file and generate style.css  -*- lexical-binding: t; -*-

;; 目标：一个 .org 文件经过 org-publish 后，在旁边自动生成 style.css。
;;
;; 该 style.css 包含当前 Emacs 主题下所有 face 的 CSS 类定义，供 ox-html
;; 导出的代码块使用。运行前请确保已加载 Modus 主题，例如：
;;
;;   (require 'modus-themes)
;;   (load-theme 'modus-operandi t)   ; 或 modus-vivendi
;;
;; 命令行执行：
;;
;;   emacs -batch -l ~/.emacs -l scripts/generate-publish.el
;;
;; 如果 modus-themes 未安装，Emacs 29+ 自带 modus-operandi / modus-vivendi。

(require 'ox-html)
(require 'ox-publish)

(defvar hugo-modus-script-dir
  (file-name-directory (or load-file-name buffer-file-name))
  "本脚本所在目录。")

(defvar hugo-modus-publish-dir
  (expand-file-name "published/" hugo-modus-script-dir)
  "org-publish 的输出目录。")

(defvar hugo-modus-style-css
  (expand-file-name "style.css" hugo-modus-publish-dir)
  "自动生成的 style.css 路径。")

(defun hugo-modus--ensure-publish-dir ()
  "确保 publish 目录存在。"
  (unless (file-directory-p hugo-modus-publish-dir)
    (make-directory hugo-modus-publish-dir t)))

(defun hugo-modus--generate-style-css (pub-dir)
  "在 PUB-DIR 中生成 style.css。
CSS 内容来自当前 Emacs 主题的所有 face 定义。"
  (let ((css-file (expand-file-name "style.css" pub-dir)))
    (org-html-htmlize-generate-css)
    (let ((css-content (buffer-string))
          (src-buffer (current-buffer)))
      (with-temp-file css-file
        (insert "/* Generated by org-html-htmlize-generate-css */\n")
        (insert css-content))
      (kill-buffer src-buffer)
      (message "Generated style.css: %s" css-file))))

(defun hugo-modus-generate-style-css (project-plist)
  "org-publish 项目完成后的回调函数。
根据 PROJECT-PLIST 中的 :publishing-directory 生成 style.css。"
  (let ((pub-dir (plist-get project-plist :publishing-directory)))
    (when pub-dir
      (hugo-modus--generate-style-css pub-dir))))

(defun hugo-modus-publish-with-style-css ()
  "Publish 脚本目录下的 .org 文件，并在完成后生成 style.css。"
  (interactive)
  (hugo-modus--ensure-publish-dir)
  (let ((org-html-htmlize-output-type 'css)
        (org-publish-project-alist
         `(("hugo-modus-publish"
            :base-directory ,hugo-modus-script-dir
            :base-extension "org"
            :publishing-directory ,hugo-modus-publish-dir
            :publishing-function org-html-publish-to-html
            :htmlized-source t
            :section-numbers nil
            :with-toc t
            :html-preamble nil
            :html-postamble nil
            :html-head "<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\"/>"
            :completion-function hugo-modus-generate-style-css))))
    (org-publish "hugo-modus-publish" t)
    (message "Published to: %s" hugo-modus-publish-dir)))

;; 非交互式运行时自动执行。
(when noninteractive
  (hugo-modus-publish-with-style-css))
